#Spring
spring:
  application:
    name: handy-logs
  datasource:
      url: ${datasource_url:jdbc:mysql://handy-staging.csojfhhlojxj.ap-southeast-1.rds.amazonaws.com:3306/backend2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false}
      username: ${datasource_username:admin}
      password: ${datasource_password:mango1501}
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      connectionTimeout: ${datasource_connectionTimeout:5000}
      idleTimeout: ${datasource_idleTimeout:600000}
      maxLifetime: ${datasource_maxLifetime:1800000}
      maximumPoolSize: ${datasource_maximumPoolSize:15}
  profiles: dev
  main:
    allow-bean-definition-overriding: true
  #zipkin
  zipkin:
    base-url: http://ec2-13-250-5-192.ap-southeast-1.compute.amazonaws.com:9411
  #kafka
  kafka:
    producer:
      bootstrap-servers: ec2-13-250-5-192.ap-southeast-1.compute.amazonaws.com:9092  
    
      
mybatis:
  mapper-locations: classpath:mapper/*.xml
  
  

server:
  port: 8089

#s3 access and bucket
aws:
  s3:
    accesskey: AKIAJ7EI4ETZJB3RRI4Q
    secretkey: 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
    bucketname: handy-backend-logs-dev
#maxfilesize unit MB
    maxfilesize: 20
#allow file type ext
    allowext: log,zip,rar,txt

#trace log topic
log:
  trace:
    local: true
    kafka:
      topic: backend2-hangpan-test
      url: http://ec2-13-250-5-192.ap-southeast-1.compute.amazonaws.com:8082/topics/backend2-hangpan-test
    
    